# Generated by Django 3.0.6 on 2020-05-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200523_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='image_category',
        ),
    ]
